version: '3.8'

services:
  caamail-api:
    image: python:3.9-slim
    ports:
      - "80:5000"
    environment:
      - SUPABASE_URL=https://fawgofnpdzyxvgupplwb.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhd2dvZm5wZHp5eHZndXBwbHdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3ODQ5ODIsImV4cCI6MjA1OTM2MDk4Mn0.yc4Aok9wlVlz5YfHKQsgNREPpyAZ47TW7JBt6bVYZvc
       - FLASK_ENV=production
      - TZ=America/Sao_Paulo
    working_dir: /app
    command: >
      bash -c "
      echo '🚀 Iniciando CAAMAIL Blacklist API...' &&
      apt-get update -qq && 
      apt-get install -y -qq gcc curl procps wget && 
      pip install --no-cache-dir --quiet Flask==2.3.3 supabase==1.3.0 python-dotenv==1.0.0 gunicorn==21.2.0 Werkzeug==2.3.7 && 
      echo '📥 Baixando código da aplicação...' &&
      curl -s -L -o main.py https://raw.githubusercontent.com/jeffersonjrpro/BlacklistCAAMG/main/main.py && 
      mkdir -p /app/logs && 
      echo '✅ Configuração concluída! Iniciando servidor...' &&
      echo '🌐 API disponível em: http://caamail.caamg.com.br' &&
      python main.py
      "
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 5s
      labels:
        - "app=caamail"
        - "version=1.0"
        - "description=CAAMAIL Blacklist API"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/status", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s 