version: '3.8'

services:
  caamail-api:
    image: python:3.9-slim
    environment:
      SUPABASE_URL: "https://fawgofnpdzyxvgupplwb.supabase.co"
      SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhd2dvZm5wZHp5eHZndXBwbHdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3ODQ5ODIsImV4cCI6MjA1OTM2MDk4Mn0.yc4Aok9wlVlz5YfHKQsgNREPpyAZ47TW7JBt6bVYZvc"
      FLASK_ENV: "production"
      TZ: "America/Sao_Paulo"
      PYTHONUNBUFFERED: "1"
    working_dir: /app
    command: ["bash", "-c", "apt-get update -qq && apt-get install -y -qq gcc curl && pip install Flask==2.3.3 supabase==2.8.0 python-dotenv==1.0.0 gunicorn==21.2.0 Werkzeug==2.3.7 && curl -s -L -o main.py https://raw.githubusercontent.com/jeffersonjrpro/BlacklistCAAMG/main/main.py && mkdir -p /app/logs && python main.py"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.caamail.rule=Host(`caamail.caamg.com.br`)"
        - "traefik.http.routers.caamail.entrypoints=web,websecure"
        - "traefik.http.services.caamail.loadbalancer.server.port=5000"
        - "traefik.http.routers.caamail.tls=true"
        - "traefik.http.routers.caamail.tls.certresolver=letsencrypt"
    networks:
      - traefik

networks:
  traefik:
    external: true 