version: '3.8'

services:
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-conf:/etc/nginx/conf.d
    depends_on:
      - caamail-api
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/caamail.conf
    deploy:
      replicas: 1
    networks:
      - caamail-network

  caamail-api:
    image: python:3.9-slim
    environment:
      - SUPABASE_URL=https://fawgofnpdzyxvgupplwb.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhd2dvZm5wZHp5eHZndXBwbHdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE5NjczMzcsImV4cCI6MjA0NzU0MzMzN30.xvI-oMwEa45LsWpPNY89R8sJJOu8Q8AJJwM_KqXKWmw
      - FLASK_ENV=production
      - TZ=America/Sao_Paulo
    working_dir: /app
    command: >
      bash -c "
      apt-get update -qq && 
      apt-get install -y -qq gcc curl procps && 
      pip install --no-cache-dir Flask==2.3.3 supabase==1.3.0 python-dotenv==1.0.0 gunicorn==21.2.0 Werkzeug==2.3.7 && 
      curl -s -L -o main.py https://raw.githubusercontent.com/jeffersonjrpro/BlacklistCAAMG/main/main.py && 
      mkdir -p /app/logs && 
      python main.py
      "
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - caamail-network

volumes:
  nginx-conf:

networks:
  caamail-network:
    driver: overlay

configs:
  nginx-config:
    external: false
    file: ./nginx.conf 