version: '3.8'

services:
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: /var/lib/docker/volumes/caamail-nginx/_data/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    command: >
      sh -c "
      echo 'server {
          listen 80;
          server_name caamail.caamg.com.br;
          
          location / {
              proxy_pass http://caamail-api:5000;
              proxy_set_header Host \$$host;
              proxy_set_header X-Real-IP \$$remote_addr;
              proxy_set_header X-Forwarded-For \$$proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto \$$scheme;
              proxy_connect_timeout 60s;
              proxy_send_timeout 60s;
              proxy_read_timeout 60s;
          }
          
          location /health {
              access_log off;
              return 200 \"healthy\n\";
              add_header Content-Type text/plain;
          }
      }' > /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'
      "
    depends_on:
      - caamail-api
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - caamail-net

  caamail-api:
    image: python:3.9-slim
    environment:
      - SUPABASE_URL=https://fawgofnpdzyxvgupplwb.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhd2dvZm5wZHp5eHZndXBwbHdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE5NjczMzcsImV4cCI6MjA0NzU0MzMzN30.xvI-oMwEa45LsWpPNY89R8sJJOu8Q8AJJwM_KqXKWmw
      - FLASK_ENV=production
      - TZ=America/Sao_Paulo
    working_dir: /app
    command: >
      bash -c "
      apt-get update -qq && 
      apt-get install -y -qq gcc curl procps && 
      pip install --no-cache-dir Flask==2.3.3 supabase==1.3.0 python-dotenv==1.0.0 gunicorn==21.2.0 Werkzeug==2.3.7 && 
      curl -s -L -o main.py https://raw.githubusercontent.com/jeffersonjrpro/BlacklistCAAMG/main/main.py && 
      mkdir -p /app/logs && 
      python main.py
      "
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - caamail-net

networks:
  caamail-net:
    driver: overlay
    attachable: true 