version: '3.8'

services:
  caamail-api:
    image: python:3.9-slim
    ports:
      - "5000:5000"
    environment:
      - SUPABASE_URL=https://fawgofnpdzyxvgupplwb.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhd2dvZm5wZHp5eHZndXBwbHdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3ODQ5ODIsImV4cCI6MjA1OTM2MDk4Mn0.yc4Aok9wlVlz5YfHKQsgNREPpyAZ47TW7JBt6bVYZvc
      - FLASK_ENV=production
      - TZ=America/Sao_Paulo
    working_dir: /app
    command: >
      bash -c "
      apt-get update -qq && 
      apt-get install -y -qq gcc curl procps && 
      pip install --no-cache-dir Flask==2.3.3 supabase==1.3.0 python-dotenv==1.0.0 gunicorn==21.2.0 Werkzeug==2.3.7 && 
      curl -s -L -o main.py https://raw.githubusercontent.com/jeffersonjrpro/BlacklistCAAMG/main/main.py && 
      mkdir -p /app/logs && 
      python main.py
      "
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M 